import = [
  "~/.config/alacritty/themes/tokyonight.toml"
]
shell = "/bin/zsh"

[window]
# padding = { x = 8, y = 8 }
title = ""
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font Propo" }
size = 10.5

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
osc52 = "CopyPaste"

[selection]
save_to_clipboard = true

