import = ["~/.config/alacritty/themes/tokyonight.toml"]

shell = "/bin/zsh"

[env]
term = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
# dynamic_padding = true
# title = ""
dynamic_title = true
# opacity = 0.86

[font]
normal = { family = "JetBrainsMono Nerd Font Propo" }
size = 10.5

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
osc52 = "CopyPaste"

[selection]
save_to_clipboard = true
